### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by k3ch0ng** [Xamarians/Xamarians.FacebookSdk#1]
Xamarians.FacebookSdk/Xamarians.FacebookLogin/Xamarians.FacebookLogin.iOS/DS/FacebookLogin.cs

AccessToken = result.Token.ToString(),
should be 
AccessToken = result.Token.TokenString.ToString(),

**Comment by Xamarians** [comment]
Thanks for your suggestion k3ch0ng .

We have fixed that bug. You can check the latest version(1.0.2). It is uploaded on the nuget.
